### PR TITLE
Fix make help description and logging info

### PR DESCRIPTION
**Pull request by mrymsza**
Add missing help description

Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/155

### CODE REVIEW

**Comment by adrianchiris** [comment]
Thanks for posting this !
needs rebasing

**Review by martinkennelly — APPROVED** [review]
/LGTM - Thank you!

**Review by adrianchiris — APPROVED** [review]

**Comment by martinkennelly** [comment]
@adrianchiris Are you happy to merge this? I see there are two approvals but I am going to wait to merge this as I see your CI has failed.

**Comment by adrianchiris** [comment]
sriov_cni_ci is passing, there is an issue reporting the results, due to some changes undergoing in our CI.
so just need to rebase and we can merge IMO.

**Comment by martinkennelly** [comment]
@mrymsza Could you rebase patch this? Thank you.

**Pull request merged**
