### PR TITLE
Delete all cached data, /bin, /build and /test directories

### PR DESCRIPTION
**Pull request by mrymsza**
Makefile should be able to delete everything it creates

Fixes https://github.com/k8snetworkplumbingwg/sriov-cni/issues/156

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]
LGTM, retriggered Mellanox CI as it might have been a temporary issue in the CI

**Review by martinkennelly — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
Checked internally, CI is passing there is an issue reporting the results which will be resolved.

**Pull request merged**
