### PR TITLE
Bump to 1.22.4

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Review by Eoghan1232 — APPROVED** [review]

**Comment by Eoghan1232** [comment]
can we also bump versions in actions too?

**Review by Eoghan1232 — APPROVED** [review]

**Comment by Eoghan1232** [comment]
CI fails on e2e tests - is this on an e2e environment?

**Comment by zeeke** [comment]
Project Dockerfile is based on `golang:alpine`, which happens to point to go1.22.4

https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/Dockerfile#L1

```
go: ../../go.mod requires go >= 1.22.4 (running go 1.22.2; GOTOOLCHAIN=local)
make: *** [Makefile:59: /usr/src/sriov-cni/build/sriov] Error 1
Error: building at STEP "RUN apk add --no-cache --virtual build-dependencies build-base=~0.5 &&     make clean &&     make build": while running runtime: exit status 2
```

@bn222 can you find an newer golang image?

**Comment by SchSeba** [comment]
I bump the image in the CI machines manually it should not support 1.22.4 lets see the CI lane

**Review by SchSeba — APPROVED** [review]
LGTM

**Pull request merged**
