### PR TITLE
Makefile refactor

### PR DESCRIPTION
**Pull request by adrianchiris**
- cleanup makefile
- update buildtest workflow
- ran go mod tidy, update go.mod

### CODE REVIEW

**Comment by adrianchiris** [comment]
similar to what was done : https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/579

**Review by zeeke — APPROVED** [review]
LGTM

I think this should solve also:
- https://github.com/k8snetworkplumbingwg/sriov-cni/issues/263

**Comment by adrianchiris** [comment]
> LGTM
> 
> I think this should solve also:
> 
> * [sriov-cni build is not idempotent #263](https://github.com/k8snetworkplumbingwg/sriov-cni/issues/263)

yeap, running make build twice will not fail :)


been looking at failed CI e2e, it dont seem to be related.

**Comment by adrianchiris** [comment]
@zeeke can we merge this one?

**Review by zeeke — APPROVED** [review]

**Comment by thom311** [comment]
```
.PHONY: all
all: fmt lint build test
```

The `all` target now also includes `test`. That seems desirable to me.

In particular, because `all` is also the default target.

On my machine, `make test` fails due to lack of permissions. Maybe I am doing it wrong, and I should develop in a new rootless netns, where I have permissions or run `make` as root(??). But I'd rather not do that (are you?)

Compare to autotools projects, where `make` does not include `make check`.

I think either:

- just don't include `test` in `all` target, as before.
- add new target (`check-and-build`) that contains `fmt lint build` (but not `test`) and which is the new default target. Like

```
.PHONY: check-and-build
check-and-build: fmt lint build

.PHONY: all
all: check-and-build test
```

**Comment by SchSeba** [comment]
agree! here with @thom311

@thom311 can you please open a PR for that?

**Pull request merged**
