### PR TITLE
return MTU in results

### PR DESCRIPTION
**Pull request by SchSeba**

### CODE REVIEW

**Comment by SchSeba** [comment]
waiting for https://github.com/k8snetworkplumbingwg/multus-cni/pull/1250

**Comment by SchSeba** [comment]
waiting for https://github.com/k8snetworkplumbingwg/sriov-cni/pull/295

**Review by zeeke — APPROVED** [review]
LGTM

**Comment by SchSeba** [comment]
Thanks for the help! 

merging this one

**Pull request merged**
