### PR TITLE
Fix checks for vlan parameters

### PR DESCRIPTION
**Pull request by mlguerrero12**
- Add check to not allow non default values of qos and proto when vlan is zero.
- Remove check when vlan is zero and qos and proto are not in config since default values are now set.

### CODE REVIEW

**Comment by mlguerrero12** [comment]
@adrianchiris, @SchSeba, @zeeke, could you please review this? The sriov network operator sets vlan and vlanQoS equal to zero by default which is a valid config. I'm removing the check that prevents that and adding back a check that I omitted in my last PR.

**Review by zeeke — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
what about vlan proto == 802.1ad and vlan==0  ?

**Comment by adrianchiris** [comment]
> nothing happens, it is ignored when vlan is set to 0 (checked with ice and mlx5 drivers). 

so its invalid  ? maybe we want to block it in cni ? currently 802.1ad and vlan=0 is allowed and as you say will work and be ignored.

**Comment by mlguerrero12** [comment]
Just to clarify, the drivers for all cases effectively set the vlan to 0. With ignore I mean the other parameters, i.e. if the qos is set to 5 and vlan to 0, the ice driver sets vlan 0 and qos 0, whereas the mlx5 sets vlan 0 and qos 5.

**Review by SchSeba — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
+1 for restricting this for now until there is a use-case for it.

its not the first time we see different behavior between drivers around VF configuration such as this.

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
