### PR TITLE
Fix mac address verification

### PR DESCRIPTION
**Pull request by SchSeba**
Before this fix there was a problem with upper or lower case mac address

### CODE REVIEW

**Comment by adrianchiris** [comment]
LGTM,

@SchSeba can you add a short description in commit msg explaining why its needed ?

**Comment by mlguerrero12** [comment]
LGTM

**Comment by adrianchiris** [comment]
There are some issues with mlnx CI should be fixed later today / tommorow.

**Comment by SchSeba** [comment]
@adrianchiris done

**Review by zeeke — APPROVED** [review]
LGTM

**Pull request merged**
